CREATE TABLE IF NOT EXISTS Characters (
    CharacterId INT AUTO_INCREMENT PRIMARY KEY,
    PlayerUserId INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Level INT NOT NULL DEFAULT 1,
    PositionX FLOAT NOT NULL DEFAULT 0.0,
    PositionY FLOAT NOT NULL DEFAULT 0.0,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PlayerUserId) REFERENCES Players(UserId) ON DELETE CASCADE,
    INDEX idx_player_id (PlayerUserId),
    INDEX idx_name (Name)
);